### PR TITLE
Fix type error when no consents have been set yet

### LINKED ISSUE #47: Error with PHP 8 when no consents given yet
```
Exception in line 120 of /…/Data/Temporary/Production/SubContextLive/SubContextWww/Cache/Code/Flow_Object_Classes/KaufmannDigital_GDPR_CookieConsent_Controller_JavaScriptController.php: in_array(): Argument #2 ($haystack) must be of type array, null given

41 in_array()
40 KaufmannDigital\GDPR\CookieConsent\Controller\JavaScriptController_Original::renderJavaScriptAction()
39 KaufmannDigital\GDPR\CookieConsent\Controller\JavaScriptController::renderJavaScriptAction()
38 KaufmannDigital\GDPR\CookieConsent\Controller\JavaScriptController::Flow_Aop_Proxy_invokeJoinPoint()
37 Neos\Flow\Aop\Advice\AdviceChain::proceed()
36 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy()
35 Neos\Flow\Aop\Advice\AroundAdvice::invoke()
34 Neos\Flow\Aop\Advice\AdviceChain::proceed()
33 KaufmannDigital\GDPR\CookieConsent\Controller\JavaScriptController::renderJavaScriptAction()
32 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
31 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest()
30 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop()
29 Neos\Flow\Mvc\Dispatcher_Original::dispatch()
28 Neos\Flow\Mvc\DispatchMiddleware_Original::process()
27 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
26 Sitegeist\Slipstream\Middleware\SlipstreamMiddleware_Original::process()
25 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
24 Neos\Flow\Http\Middleware\SecurityEntryPointMiddleware_Original::process()
23 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
22 Neos\Flow\Http\Middleware\RequestBodyParsingMiddleware_Original::process()
21 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
20 Neos\Flow\Mvc\FlashMessage\FlashMessageMiddleware_Original::process()
19 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
18 Neos\Flow\Http\Middleware\PoweredByMiddleware_Original::process()
17 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
16 Neos\RedirectHandler\RedirectMiddleware_Original::process()
15 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
14 Neos\Flow\Mvc\Routing\RoutingMiddleware_Original::process()
13 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
12 Neos\Neos\Routing\RequestUriHostMiddleware_Original::process()
11 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
10 Neos\FluidAdaptor\Core\Widget\AjaxWidgetMiddleware_Original::process()
9 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
8 Neos\Flow\Http\Middleware\SessionMiddleware_Original::process()
7 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
6 Neos\Flow\Http\Middleware\TrustedProxiesMiddleware_Original::process()
5 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
4 Neos\Flow\Http\Middleware\StandardsComplianceMiddleware_Original::process()
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()

HTTP REQUEST:
target: /api/kd-gdpr-cc.js?dimensions%5Blanguage%5D%5B0%5D=en_GB&dimensions%5Blanguage%5D%5B1%5D=de
Host: www.redacted.de
Referer: https://www.redacted.de/en/pictures/something.html
Accept-Language: en-GB,en;q=0.9
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1
Accept-Encoding: gzip, deflate, br
Accept: */*

PHP PROCESS:
Inode: 4862331
PID: 1334685
```

### PR DESCRIPTION
**Pull request by kdambekalns**
Make sure `$consents` is an array instead of `null` when not set in `$cookie` at all.

Fixes #47

### CODE REVIEW

**Comment by Nikdro** [comment]
Thanks for your PR @kdambekalns! 

Unfortunately, I could not recreate the problem. The code is located in a try-catch block. This should actually ensure that these exceptions get catched and an empty JavaScript is generated, as long as not all necessary parameters are set via the cookie. 

In my tests, the whole thing worked, so that it never came to the error (PHP 8.1). Only if I remove the try-catch block, I get an error.   
The fix does not lead to any other error, but I still get other exceptions with the fix, which lead to the same result with try-catch.  

Maybe I'm missing something and you can help me out.... 
You can also reach my via Slack, if thats easier :)

**Review by Nikdro — APPROVED** [review]
Shouldn't break something. Even not in my tests.

**Comment by Nikdro** [comment]
Hi @kdambekalns, I wasn't able again to reproduce your described problem. But since this should not break something and it worked for me in my tests, I'll get this into v5 now.

**Comment by kdambekalns** [comment]
Sorry for not getting back to this, I had hoped to find time to verify it again. But the issue was real… 🤷‍♂️

Thanks for merging! ❤️‍🔥

**Pull request merged**
