### PR TITLE
Language additions and fixes

### PR DESCRIPTION
**Pull request by hphoeksma**
Adds a missing language label, adds a few languages and cleans up some of the xlf files.

I would suggest to remove the `xml:space="preserve"` attributes throughout all languages files. Happy to do this.

Fixes: #57

### CODE REVIEW

**Review by Nikdro — APPROVED** [review]
Looking good from first code-view. 

I'll do a test, together with other changes, before merging.

**Comment by Nikdro** [comment]
@hphoeksma Thanks for your PR, looking good so far. As mentioned in the comment above, I'll do some checks and then release a new Version, together with other upcoming changes. Should be done by tomorrow. 

Can you explain me the benefit of removing the `xml:space="preserve"` from xlf files? To be hornest, I've got no idea why it is there. Probably we just copied the XLF-structure from original Neos xlf files and kept it that way.

**Comment by hphoeksma** [comment]
@Nikdro I started out the same, copying the original Neos files and change those. However I have found the formatting the XLF files is a pain when using xml:space="preserve". What I understand is that this is used for values where line breaks, tabs, spaces etc are important. I usually only use this parameter when I see it is needed (which is never since where whitespace is relevant I am always in need of the `<CDATA[ ... ]]>` encapsulating...
I also noticed weblate (which I use mostly when dealing with lots of files) don't add this attribute.

**Comment by Nikdro** [comment]
Thanks for your Feedback @hphoeksma! 

Would you do that changes and add it to this PR/branch? Then I'll do my tests also with that one included and it could go into the new version. Thanks!

**Comment by hphoeksma** [comment]
Sure, I hope to be able to do this today!

**Review by Nikdro — APPROVED** [review]

**Comment by Nikdro** [comment]
Thanks again! This is now included in 5.4.0

**Pull request merged**
